### PR TITLE
make shell-mommy work with POSIX shell

### PR DESCRIPTION
**Pull request by CorruptedVor**
MOMMY_DIR wasn't being used, so I completely removed it.

### CODE REVIEW

**Comment by y0nei** [comment]
works on bash, fails on zsh
```console
mommy:67: = not found
```

**Comment by CorruptedVor** [comment]
> 

thanks, fixed

**Comment by y0nei** [comment]
sed now throws an error for me on like 83
```shell
echo "$1" | sed 's/\/\//\n/g' | shuf | sed 1q
```
how did you test this?

**Comment by CorruptedVor** [comment]
> sed now throws an error for me on like 83
> 
> ```shell
> echo "$1" | sed 's/\/\//\n/g' | shuf | sed 1q
> ```
> 
> how did you test this?

I just went
```
zsh
source shell-mommy.sh
mommy ls```
what's the error?

**Comment by FWDekker** [comment]
I didn't know this project existed until just now, but as it happens I wrote my own version of mommy for shells. It works on any POSIX system (Linux/macOS/*BSD are all tested), and also works in any shell (zsh, fish, bash, dash, etc.), and the README has instructions on how to integrate it with those shells:  https://github.com/FWDekker/mommy

**Comment by sudofox** [comment]
I've been away. Is this PR working on zsh now?

**Comment by CorruptedVor** [comment]
> I've been away. Is this PR working on zsh now?

As far as I can tell, yes. @y0nei had an error but that should be fixed

**Comment by sudofox** [comment]
Coolio.

**Pull request merged**
